version: 2
updates:
  - package-ecosystem: "github-actions"
    directory: ".github/workflows" # Location of package manifests
    schedule:
      interval: "monthly"
    groups:
      actions:
        patterns:
          - "*"
