version: 2

build:
  os: "ubuntu-lts-latest"
  tools:
    python: "3.13"

python:
  install:
    - requirements: docs/requirements.txt

# Don't build any extra formats
formats: []

sphinx:
  configuration: docs/conf.py
